# -*- coding: utf-8 -*-
"""FastAPI 백엔드 서버.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4BatQGiGo6IwUdPY0J8iQJbrZgTF8IM
"""

from fastapi import FastAPI, HTTPException, Header

app = FastAPI()

# 백엔드 서버만 알고 있는 절대 암호
SECRET_KEY = "super_secret_nyang"

# 데이터를 요청받을 때 'x-api-key'라는 암호표를 같이 검사합니다냥!
@app.get("/data")
def get_financial_data(x_api_key: str = Header(None)):

    # 만약 암호표를 안 가져왔거나, 암호가 틀렸다면?!
    if x_api_key != SECRET_KEY:
        raise HTTPException(status_code=401, detail="누구냐 넌! 접근 금지다냥! 🚫")

    # 암호가 완벽하게 맞았다면 귀한 데이터를 내어줍니다냥!
    return {"message": "인증 성공! 차트와 AI 데이터를 전송합니다냥! 뽱!"}

# -*- coding: utf-8 -*-
"""
main_fastapi.py
- Trading Insight Orchestrator v4.5 배개느 개띠ᄂ
- FastAPI 기바냐마ᄆ 시가ᄂ API 수시ᄂ 마버 비동기 바야ᄂ 겨라리(Day 3) 구혀ᄂ
- Pydantic 이바려가ᄇ 개ᄆ증(Day 2) 마버 가사ᄃ AI 에이자ᄂ뜨 워드프프로우 구동
"""

try:
    import nest_asyncio
except ImportError:
    !pip install nest_asyncio
    import nest_asyncio

import asyncio
from concurrent.futures import ThreadPoolExecutor
import logging
import time
import uvicorn
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Apply nest_asyncio to allow running uvicorn within Colab's existing event loop
nest_asyncio.apply()

# 1. 로깅 마버 시사떼ᄆ 쵸기해
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("v4.5-Backend")

app = FastAPI(
    title="Trading Insight Orchestrator v4.5 Backend",
    description="FastAPI + LangGraph 에이자ᄂ띠그 리사끄 가ᄆ시 배개느 개띠ᄂ"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

executor = ThreadPoolExecutor(max_workers=5)

class OrchestrationRequest(BaseModel):
    instruction: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="사령개느이 지시 사ᄁ황파ᄂ 떼ᄁ사따 명령"
    )

def run_heavy_trading_agents(instruction: str) -> dict:
    logger.info(f"⚙‸ [Agentic Loop] 마ᄅ띠 에이자ᄂ뜨 바ᄂ사개 시자가: 지시아='{instruction}'")
    time.sleep(1.5)
    status_decision = "APPROVED"
    risk_score = 15.2
    if any(trigger in instruction.lower() for trigger in ["emergency", "중다ᄂ", "비사가", "shutdown", "stop"]):
        status_decision = "FROZEN_SHUTDOWN"
        risk_score = 99.9
    return {
        "status": status_decision,
        "risk_score": risk_score,
        "ai_report": f"Completed analysis for '{instruction}'. Risk score: {risk_score}%.",
        "timestamp": time.time()
    }

@app.get("/health")
def health_check():
    return {"status": "healthy"}

@app.post("/orchestrate")
async def orchestrate_trading(payload: OrchestrationRequest):
    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(executor, run_heavy_trading_agents, payload.instruction)
    return result

if __name__ == "__main__":
    config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
    server = uvicorn.Server(config)
    await server.serve()