# -*- coding: utf-8 -*-
"""Streamlit 프론트엔드 대시보드.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TaJcmiSaaKjQ4uhRjxhNaFZasee7MOuc
"""

import streamlit as st

# 1. 비밀번호 입력창 만들기 (type="password"를 쓰면 글자가 *** 로 가려집니다냥!)
password = st.text_input("떵컴 V4.5 1급 기밀 암호를 입력하시오냥:", type="password")

# 2. 암호가 틀리면 여기서 멈춰버리기!
if password != "nyang1234":  # 조장님만의 비밀번호로 바꾸셔요!
    st.warning("경고! 인가되지 않은 접근입니다냥! 🚨")
    st.stop() # 뽱!!! 이 밑으로는 코드 실행을 아예 차단해버립니다.

# 3. 암호가 맞으면 무사 통과!
st.success("얄공 조장님 환영합니다냥!!! 보안 해제 완료! 🔓")
st.title("📈 V4.5 금융 AI 오케스트레이터 실가동!!!")

# --- 이 아래부터 원래 짜두셨던 차트 및 AI 코드를 두시면 됩니다냥! ---

# -*- coding: utf-8 -*-
"""
app_streamlit.py
- Trading Insight Orchestrator v4.5 프론트엔드 대시보드
- Streamlit 기반의 인터랙티브 UI 및 실시간 시각화 뷰판 구현
- st.session_state 기반의 상태 유지 및 st.cache_resource를 통한 최적화
"""

!pip install streamlit
import streamlit as st
import requests
import time

# 1. 페이지 기본 레이아웃 및 UX 옵션 설정
st.set_page_config(
    page_title="Trading Orchestrator v4.5 Dashboard",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# 백엔드 기지국 포트 주소 정의 (FastAPI 주소)
BACKEND_URL = "http://localhost:8000"

# 2. 세션 상태 저장소 초기화 (Rerun 메커니즘 대응용)
if "audit_history" not in st.session_state:
    st.session_state.audit_history = []
if "is_frozen" not in st.session_state:
    st.session_state.is_frozen = False

# 3. 대시보드 타이틀 영역
st.title("🏆 Trading Insight Orchestrator v4.5")
st.subheader("인간 개입형(Human-in-the-Loop) 실시간 대시보드 및 지시 상황판")

# 4. 좌우 화면 분할 배치 (UX 시각화 구조)
col_left, col_right = st.columns([2, 1])

# --- 왼쪽: 차트 및 에이전트 리포트 뷰판 영역 ---
with col_left:
    st.markdown("### 📊 실시간 분석 리포트 및 시장 뷰판")

    # 백엔드 기지국 건강 상태 체크
    try:
        response = requests.get(f"{BACKEND_URL}/health", timeout=1.5)
        if response.status_code == 200:
            st.success("🟢 실시간 가상환경 백엔드 엔진 연동 중 (Port: 8000)")
        else:
            st.warning("🟡 백엔드 기지국 응답이 원활하지 않습니다.")
    except requests.exceptions.ConnectionError:
        st.error("🔴 [네트워크 비상상황] 8000번 백엔드 서버가 다운되었습니다. 즉시 확인하십시오.")
        st.session_state.is_frozen = True

    # 가상 트레이딩뷰 차트 프레임 시각화
    st.info("💡 트레이딩뷰 차트 시각화 및 에이전트 종합 보고서 대기 공간")

    # 간단한 가이드 차트 모사
    chart_data = [10, 15, 8, 22, 18, 30, 45, 38, 55]
    st.line_chart(chart_data)
    st.caption("※ 실시간 데이터 흐름 및 기술적 보조 지표 뷰판 시뮬레이션")

# --- 오른쪽: 조장님 지시상황판 및 물리 비상벨 영역 ---
with col_right:
    st.markdown("### 🚨 실전 지시 상황판 및 비상 벨")

    # 비상벨 상태 시각화 제어 (UX 가드레일)
    if st.session_state.is_frozen:
        st.error("⛔ [FROZEN] 모든 자동 매매 파이프라인이 임시 동결되었습니다.")

    # 텍스트 지시 입력 컨트롤
    user_feedback = st.text_input(
        "사령관 지시 사항 입력 (예: Emergency, 매수 보류, 롱 진격)",
        placeholder="지시 문맥을 기재하세요...",
        disabled=st.session_state.is_frozen,
        key="cmd_input"
    )

    col_btn1, col_btn2 = st.columns(2)

    with col_btn1:
        # 사격 개시 버튼 (FastAPI 백엔드로 명령 전송)
        if st.button("🚀 사격 개시 (승인)", use_container_width=True, disabled=st.session_state.is_frozen):
            if user_feedback:
                with st.spinner("가상환경 내 에이전트단 검증 통과 중..."):
                    try:
                        # FastAPI 백엔드로 Pydantic 규격에 맞춰 JSON 데이터 전송 (Day 2 & Day 4 융합)
                        payload = {"instruction": user_feedback}
                        res = requests.post(f"{BACKEND_URL}/orchestrate", json=payload, timeout=5)

                        if res.status_code == 200:
                            result_data = res.json()
                            # 세션 상태에 이력 누적하여 Rerun 시에도 보존 (Day 4 핵심)
                            st.session_state.audit_history.append({
                                "time": time.strftime("%H:%M:%S"),
                                "cmd": user_feedback,
                                "status": result_data["status"],
                                "risk": result_data["risk_score"],
                                "report": result_data["ai_report"]
                            })

                            # 비상벨 키워드로 인한 동결 여부 판독
                            if result_data["status"] == "FROZEN_SHUTDOWN":
                                st.session_state.is_frozen = True

                            st.success("✅ 주문 집행 검증 프로세스 가동 완료")
                        elif res.status_code == 422:
                            st.error("❌ [422] 전송된 데이터 규격에 무결성 결함이 있습니다.")
                    except Exception as e:
                        st.error(f"⚠️ 백엔드 통신 실패: {str(e)}")
            else:
                st.warning("지시 사항을 먼저 입력해 주십시오.")

    with col_btn2:
        # 물리 비상벨 버튼 (누르는 즉시 프론트엔드 자체 상태 즉각 동결)
        if st.button("🛑 EMERGENCY (비상벨)", type="primary", use_container_width=True):
            st.session_state.is_frozen = True
            st.session_state.audit_history.append({
                "time": time.strftime("%H:%M:%S"),
                "cmd": "EMERGENCY_SHUTDOWN_CLICKED",
                "status": "FROZEN_SHUTDOWN",
                "risk": 100.0,
                "report": "사령관 프론트엔드 비상 제동 긴급 실행함."
            })
            # 바뀐 동결 상태를 즉시 렌더링하기 위해 강제 Rerun 실행
            st.rerun()

    # 시스템 초기화용 버튼 (테스트 편의용)
    if st.button("🔄 시스템 리셋 (개발자 전용)", use_container_width=True):
        st.session_state.is_frozen = False
        st.session_state.audit_history = []
        st.rerun()

    # 지시 및 통제 감사 이력 모니터링 출력
    st.markdown("#### 📜 최근 제어 감사 로그 (Audit History)")
    if st.session_state.audit_history:
        for idx, log in enumerate(reversed(st.session_state.audit_history[-5:])):
            st.write(f"[{log['time']}] `{log['cmd']}` ➔ **{log['status']}** (위험도: {log['risk']}%))")
            st.caption(f"↳ {log['report']}")
    else:
        st.write("대기 상태: 전송된 제어 명령이 없습니다.")

import streamlit as st
import requests

# ==========================================
# 🛡️ [1단계] 스트림릿 도어락 (프론트엔드 방어막)
# ==========================================
password = st.text_input("떵컴 V4.5 1급 기밀 암호를 입력하시오냥:", type="password")

# 암호가 틀리면 여기서 가차 없이 코드를 멈춰버립니다 뽱!
if password != "nyang1234":
    st.warning("경고! 인가되지 않은 접근입니다냥! 🚨")
    st.stop()

# 암호가 맞으면 이 아래로 넘어옵니다냥!
st.success("얄공 조장님 환영합니다냥!!! 보안 해제 완료! 🔓")
st.title("📈 V4.5 금융 AI 오케스트레이터 실가동!!!")

st.divider() # 화면에 예쁜 가로줄 긋기 뽱!

# ==========================================
# 🕵️‍♂️ [3단계] 백엔드에 암호표 던지며 데이터 가져오기
# ==========================================
backend_url = "http://127.0.0.1:8000/data" # 조장님의 FastAPI 백엔드 주소

# 백엔드 초병(FastAPI)에게 보여줄 1급 기밀 암호표 (헤더)
headers = {"x-api-key": "super_secret_nyang"}

# 조장님이 버튼을 누르면 데이터를 뽱! 가져옵니다.
if st.button("위대한 떵컴 서버에서 데이터 가져오기 뽱!!!"):

    # 3단계 핵심: headers 주머니에 암호표를 넣어서 백엔드로 쏩니다냥!
    response = requests.get(backend_url, headers=headers)

    # 백엔드 초병이 암호를 확인하고 문을 열어줬다면 (상태코드 200번)
    if response.status_code == 200:
        st.write("백엔드 침투 완벽 성공!!! 뽱!!!", response.json())
        # (여기에 조장님이 그리시려던 삐까뻔쩍한 금융 차트 코드를 넣으시면 됩니다냥!)
    else:
        st.error("백엔드 접근 실패냥!!! FastAPI 암호를 다시 확인하십쇼!!!")