[project]
name = "tradingview_api_real_time_trading_system"
version = "0.1.0"
description = "tradingview_api_real_time_trading_system using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[anthropic,file-processing,litellm,tools]==1.14.4",
]

[project.scripts]
tradingview_api_real_time_trading_system = "tradingview_api_real_time_trading_system.main:run"
run_crew = "tradingview_api_real_time_trading_system.main:run"
train = "tradingview_api_real_time_trading_system.main:train"
replay = "tradingview_api_real_time_trading_system.main:replay"
test = "tradingview_api_real_time_trading_system.main:test"
run_with_trigger = "tradingview_api_real_time_trading_system.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[tool.uv]
override-dependencies = ["litellm<=1.82.6"]
